version: '2'
services:
  php:
    build: ./Dockerfiles/php/.
    volumes:
      - ./src:/var/www/html
    ports:
      - '80:80'
  mysql:
    build: ./Dockerfiles/mysql/. 
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password